#!/usr/bin/env node
/**
 * Automated wiki manager for 9898-MTG Chaos RPG.
 *
 * Regenerates the GitHub wiki pages from repository content so the wiki
 * stays in sync with README, docs/, world-building, mechanics and source.
 *
 * Usage:
 *   node tools/manage-wiki.js --out <wiki-checkout-dir>
 *
 * The script is idempotent: running it repeatedly with the same repo
 * contents produces the same wiki files. The calling workflow is
 * responsible for cloning the wiki (`<repo>.wiki.git`), invoking this
 * script against that checkout, and committing/pushing any changes.
 */

import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, '..');

function parseArgs(argv) {
    const args = { out: null };
    for (let i = 2; i < argv.length; i++) {
        const a = argv[i];
        if ((a === '--out' || a === '-o') && argv[i + 1]) {
            args.out = argv[++i];
        } else if (a.startsWith('--out=')) {
            args.out = a.slice('--out='.length);
        } else if (a === '--help' || a === '-h') {
            args.help = true;
        }
    }
    return args;
}

async function readFileSafe(rel) {
    try {
        return await fs.readFile(path.join(repoRoot, rel), 'utf8');
    } catch {
        return null;
    }
}

async function writePage(outDir, name, body) {
    const filePath = path.join(outDir, name);
    const normalized = body.endsWith('\n') ? body : `${body}\n`;
    await fs.mkdir(path.dirname(filePath), { recursive: true });
    await fs.writeFile(filePath, normalized, 'utf8');
    return filePath;
}

const GENERATED_BANNER = [
    '<!--',
    '  This page is auto-generated by tools/manage-wiki.js on a weekly',
    '  schedule (see .github/workflows/weekly-wiki.yml). Manual edits will',
    '  be overwritten. Update the source files in the main repository',
    '  instead.',
    '-->',
    '',
].join('\n');

function buildHome(readme) {
    const intro =
        readme
            ?.split('\n')
            .slice(0, 40)
            .join('\n')
            .replace(/^#\s+.*$/m, '# 9898-MTG Chaos RPG Wiki') ?? '# 9898-MTG Chaos RPG Wiki';

    const nav = [
        '## Wiki Contents',
        '',
        '- [[Getting Started]] - install, run, and play',
        '- [[World Building]] - lore, towns, factions',
        '- [[Mechanics]] - MTG RPG interaction tables and rules',
        '- [[Tutorial Handbook]] - guides and FAQs',
        '- [[Bosses]] - Master Bosses reference',
        '- [[Generators]] - Perchance generator catalog',
        '- [[Module Reference]] - source module index',
        '- [[Contributing]] - how to contribute',
        '- [[Security]] - security policy',
        '',
    ].join('\n');

    return `${GENERATED_BANNER}${intro}\n\n${nav}`;
}

function buildGettingStarted(readme) {
    if (!readme) {
        return `${GENERATED_BANNER}# Getting Started\n\nSee the repository README for setup instructions.\n`;
    }
    // Extract the section starting from a heading that includes "Getting Started"
    // or fall back to the first "Quick Start" / "Installation" section.
    const lines = readme.split('\n');
    const startIdx = lines.findIndex((l) =>
        /^#{1,3}\s+(getting started|quick start|installation|setup)/i.test(l)
    );
    let body;
    if (startIdx >= 0) {
        const level = (lines[startIdx].match(/^#+/) || ['#'])[0].length;
        let endIdx = lines.length;
        for (let i = startIdx + 1; i < lines.length; i++) {
            const m = lines[i].match(/^(#+)\s+/);
            if (m && m[1].length <= level) {
                endIdx = i;
                break;
            }
        }
        body = lines.slice(startIdx, endIdx).join('\n');
    } else {
        body = `# Getting Started\n\n${readme}`;
    }
    return `${GENERATED_BANNER}${body}\n`;
}

function buildFromMarkdown(source, fallbackTitle) {
    if (!source) {
        return `${GENERATED_BANNER}# ${fallbackTitle}\n\n_Source file not found in repository._\n`;
    }
    return `${GENERATED_BANNER}${source.trim()}\n`;
}

async function buildModuleReference() {
    const roots = ['src', 'js', 'tools'];
    const lines = ['# Module Reference', '', 'Auto-generated index of source modules.', ''];
    for (const root of roots) {
        const abs = path.join(repoRoot, root);
        let stat;
        try {
            stat = await fs.stat(abs);
        } catch {
            continue;
        }
        if (!stat.isDirectory()) {
            continue;
        }
        lines.push(`## ${root}/`, '');
        const entries = await walk(abs);
        entries.sort();
        for (const entry of entries) {
            const rel = path.relative(repoRoot, entry).replace(/\\/g, '/');
            const doc = await extractLeadingDoc(entry);
            lines.push(`- \`${rel}\`${doc ? ` - ${doc}` : ''}`);
        }
        lines.push('');
    }
    return `${GENERATED_BANNER}${lines.join('\n')}`;
}

async function walk(dir) {
    const out = [];
    const stack = [dir];
    while (stack.length) {
        const cur = stack.pop();
        let ents;
        try {
            ents = await fs.readdir(cur, { withFileTypes: true });
        } catch {
            continue;
        }
        for (const ent of ents) {
            const full = path.join(cur, ent.name);
            if (ent.isDirectory()) {
                if (ent.name === 'node_modules' || ent.name.startsWith('.')) {
                    continue;
                }
                stack.push(full);
            } else if (ent.isFile() && /\.(js|mjs|cjs)$/.test(ent.name)) {
                out.push(full);
            }
        }
    }
    return out;
}

async function extractLeadingDoc(file) {
    let text;
    try {
        text = await fs.readFile(file, 'utf8');
    } catch {
        return null;
    }
    const block = text.match(/\/\*\*([\s\S]*?)\*\//);
    if (block) {
        const first = block[1]
            .split('\n')
            .map((l) => l.replace(/^\s*\*\s?/, '').trim())
            .find((l) => l && !l.startsWith('@'));
        if (first) {
            return first.slice(0, 160);
        }
    }
    const m = text.match(/^\s*\/\/\s*(.+)$/m);
    return m ? m[1].trim().slice(0, 160) : null;
}

async function buildBosses() {
    const src = await readFileSafe('src/core/gameState.js');
    const lines = ['# Bosses', ''];
    if (!src) {
        lines.push('_Source `src/core/gameState.js` not found._');
        return `${GENERATED_BANNER}${lines.join('\n')}\n`;
    }
    // Extract objects that look like boss records: { id: '...', name: '...', ... }
    // We do a lightweight regex sweep for id/name pairs inside a `bosses:` array.
    const bossesBlock = src.match(/bosses\s*:\s*\[([\s\S]*?)\n\s*\]/);
    if (!bossesBlock) {
        lines.push('_Could not locate `bosses` array in gameState.js._');
        return `${GENERATED_BANNER}${lines.join('\n')}\n`;
    }
    const objRe = /\{([\s\S]*?)\}/g;
    let m;
    let count = 0;
    while ((m = objRe.exec(bossesBlock[1])) !== null) {
        const body = m[1];
        const id = (body.match(/id\s*:\s*['"]([^'"]+)['"]/) || [])[1];
        const name = (body.match(/name\s*:\s*['"]([^'"]+)['"]/) || [])[1];
        const health = (body.match(/(?:^|[,{\s])health\s*:\s*(\d+)/) || [])[1];
        const difficulty = (body.match(/difficulty\s*:\s*(\d+)/) || [])[1];
        const location = (body.match(/location\s*:\s*['"]([^'"]+)['"]/) || [])[1];
        if (!id && !name) {
            continue;
        }
        count++;
        lines.push(`## ${name || id}`, '');
        if (id) {
            lines.push(`- **ID**: \`${id}\``);
        }
        if (health) {
            lines.push(`- **Health**: ${health}`);
        }
        if (difficulty) {
            lines.push(`- **Difficulty**: ${difficulty}`);
        }
        if (location) {
            lines.push(`- **Location**: ${location}`);
        }
        lines.push('');
    }
    if (count === 0) {
        lines.push('_No boss entries could be parsed._');
    }
    return `${GENERATED_BANNER}${lines.join('\n')}\n`;
}

async function buildGenerators() {
    const src = await readFileSafe('src/generators/perchance.js');
    const lines = [
        '# Generators',
        '',
        'Perchance-compatible content generators registered by default.',
        '',
    ];
    if (!src) {
        lines.push('_Source `src/generators/perchance.js` not found._');
        return `${GENERATED_BANNER}${lines.join('\n')}\n`;
    }
    const re = /this\.addGenerator\(\s*['"]([A-Za-z0-9_]+)['"]/g;
    const names = new Set();
    let m;
    while ((m = re.exec(src)) !== null) {
        names.add(m[1]);
    }
    if (names.size === 0) {
        lines.push('_No generators discovered._');
    } else {
        for (const n of [...names].sort()) {
            lines.push(`- \`${n}\``);
        }
    }
    return `${GENERATED_BANNER}${lines.join('\n')}\n`;
}

function buildSidebar() {
    const items = [
        '### Navigation',
        '',
        '- [[Home]]',
        '- [[Getting Started]]',
        '- [[World Building]]',
        '- [[Mechanics]]',
        '- [[Tutorial Handbook]]',
        '- [[Bosses]]',
        '- [[Generators]]',
        '- [[Module Reference]]',
        '- [[Contributing]]',
        '- [[Security]]',
        '',
    ];
    return `${GENERATED_BANNER}${items.join('\n')}`;
}

function buildFooter() {
    const stamp = new Date()
        .toISOString()
        .replace('T', ' ')
        .replace(/\.\d+Z$/, ' UTC');
    return `${
        GENERATED_BANNER
    }Auto-synced from [adamf9898/9898-MTG-Chaos-RPG](https://github.com/adamf9898/9898-MTG-Chaos-RPG) on ${stamp}.\n`;
}

async function main() {
    const args = parseArgs(process.argv);
    if (args.help || !args.out) {
        process.stdout.write(
            'Usage: node tools/manage-wiki.js --out <wiki-checkout-dir>\n' +
                '\n' +
                'Regenerates wiki pages inside the given checkout of the GitHub wiki repo.\n'
        );
        process.exit(args.help ? 0 : 1);
    }
    const outDir = path.resolve(args.out);
    await fs.mkdir(outDir, { recursive: true });

    const readme = await readFileSafe('README.md');
    const world = await readFileSafe('world-building-wiki.md');
    const mech = await readFileSafe('mechanics-development.md');
    const tut = await readFileSafe('docs/practical-tutorial-handbook.md');
    const contrib = await readFileSafe('CONTRIBUTING.md');
    const security = await readFileSafe('SECURITY.md');

    const pages = [
        ['Home.md', buildHome(readme)],
        ['Getting-Started.md', buildGettingStarted(readme)],
        ['World-Building.md', buildFromMarkdown(world, 'World Building')],
        ['Mechanics.md', buildFromMarkdown(mech, 'Mechanics')],
        ['Tutorial-Handbook.md', buildFromMarkdown(tut, 'Tutorial Handbook')],
        ['Bosses.md', await buildBosses()],
        ['Generators.md', await buildGenerators()],
        ['Module-Reference.md', await buildModuleReference()],
        ['Contributing.md', buildFromMarkdown(contrib, 'Contributing')],
        ['Security.md', buildFromMarkdown(security, 'Security')],
        ['_Sidebar.md', buildSidebar()],
        ['_Footer.md', buildFooter()],
    ];

    const written = [];
    for (const [name, body] of pages) {
        const p = await writePage(outDir, name, body);
        written.push(path.relative(outDir, p));
    }

    process.stdout.write(`Wrote ${written.length} wiki page(s) to ${outDir}:\n`);
    for (const w of written) {
        process.stdout.write(`  - ${w}\n`);
    }
}

main().catch((err) => {
    process.stderr.write(`manage-wiki failed: ${err.stack || err.message}\n`);
    process.exit(1);
});
